config/routes.rb
Rails.application.routes.draw do
  resources :staticpages
  root "staticpages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/staticpage.rb
class Staticpage < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController

  def index
    flickr = Flickr.new(ENV['FLICKR_API_KEY'], ENV['FLICKR_SHARED_SECRET'])
    user_id = params[:flickr_id]
    begin
        @photo_urls = flickr.people.getPublicPhotos(user_id: user_id)
    rescue Flickr::FailedResponse => e
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flickrfeed</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple-v1.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/staticpages/_form.html.erb
<%= form_with(model: staticpage) do |form| %>
  <% if staticpage.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(staticpage.errors.count, "error") %> prohibited this staticpage from being saved:</h2>

      <ul>
        <% staticpage.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :flickr_id, style: "display: block" %>
    <%= form.text_field :flickr_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/staticpages/edit.html.erb
<%# <h1>Editing staticpage</h1>

 render "form", staticpage: @staticpage %>
<%# 
<br>

<div>
   link_to "Show this staticpage", @staticpage %> |
   <%# link_to "Back to staticpages", staticpages_path
</div>  %>

app/views/staticpages/index.html.erb
<div id="staticpages">
<%= form_with method: :get, url: staticpages_path do |form| %>
    <%= form.label :flickr_id, "Enter a flickr user id: "%>
    <%= form.text_field :flickr_id, placeholder: "197774467@N07" %>
    <%= form.submit "Search" %>
<% end %>
<% begin %>
    <% @photo_urls.each do |url| %>
        <%= image_tag Flickr.url_q(url) %>
    <% end %>
<% rescue StandardError => e %>
<% end %>
</div>

app/views/staticpages/new.html.erb
<%# <h1>New staticpage</h1>

<%= render "form", staticpage: @staticpage %>
<%# 
<br>

<div>
   link_to "Back to staticpages", staticpages_path 
</div> %>